version: "3.5"

services:
  test1:
    image: my_custom_node_image
    command: node -e "const http = require('http'); http.createServer((req, res) => { res.write('Hello from <strong>test1</strong>'); res.end() }).listen(8080)"
    ports:
      - "8081:8080"
    networks:
      - network1
  test2:
    image: my_custom_node_image
    command: node -e "const http = require('http'); http.createServer((req, res) => { res.write('Hello from <strong>test2</strong>'); res.end() }).listen(8080)"
    ports:
      - "8082:8080"
    networks:
      - network1
      - network2
  test3:
    image: my_custom_node_image
    command: node -e "const http = require('http'); http.createServer((req, res) => { res.write('Hello from <strong>test3</strong>'); res.end() }).listen(8080)"
    ports:
      - "8083:8080"
    networks:
      - network2

networks:
  network1:
    name: network1
    driver: bridge
  network2:
    name: network2
    driver: bridge
